extends Node

var words : Array[Word] = [
	Word.new("and", Word.Type.OTHER, 1, Word.Rhyme.AND),
	Word.new("bet", Word.Type.VERB, 1, Word.Rhyme.ET),
	Word.new("i", Word.Type.NOUN, 1, Word.Rhyme.HY),
	Word.new("i'd", Word.Type.OTHER, 1, Word.Rhyme.IED),
	Word.new("i'll", Word.Type.OTHER, 1, Word.Rhyme.ILL),
	Word.new("i'm", Word.Type.OTHER, 1, Word.Rhyme.NONE),
	Word.new("only", Word.Type.OTHER, 1, Word.Rhyme.ONLY),
	Word.new("so", Word.Type.OTHER, 1, Word.Rhyme.NONE),
	Word.new("stop", Word.Type.VERB, 1, Word.Rhyme.OP),
	Word.new("take", Word.Type.VERB, 1, Word.Rhyme.AKE),
	Word.new("where", Word.Type.ADVERB, 1, Word.Rhyme.AIR),
	Word.new("why", Word.Type.ADVERB, 1, Word.Rhyme.HY),
	Word.new("you're", Word.Type.OTHER, 2, Word.Rhyme.URE),
	Word.new("your", Word.Type.OTHER, 1, Word.Rhyme.URE),
	Word.new("a", Word.Type.OTHER, 1, Word.Rhyme.AYE),
	Word.new("afford", Word.Type.VERB, 2, Word.Rhyme.ORD),
	Word.new("are", Word.Type.OTHER, 1, Word.Rhyme.ARE),
	Word.new("as", Word.Type.OTHER, 1, Word.Rhyme.AZ),
	Word.new("be", Word.Type.OTHER, 1, Word.Rhyme.EE),
	Word.new("being", Word.Type.VERB, 1, Word.Rhyme.EING),
	Word.new("better", Word.Type.ADJECTIVE, 2, Word.Rhyme.ETTER),
	Word.new("born", Word.Type.VERB, 1, Word.Rhyme.ORN),
	Word.new("broke", Word.Type.ADJECTIVE, 1, Word.Rhyme.OKE),
	Word.new("cannot", Word.Type.OTHER, 2, Word.Rhyme.OT),
	Word.new("can't", Word.Type.OTHER, 1, Word.Rhyme.ANT),
	Word.new("child", Word.Type.OTHER, 1, Word.Rhyme.ILD),
	Word.new("cooler", Word.Type.OTHER, 2, Word.Rhyme.OLER),
	Word.new("could", Word.Type.OTHER, 1, Word.Rhyme.OULD),
	Word.new("couldn't", Word.Type.OTHER, 2, Word.Rhyme.INT),
	Word.new("did", Word.Type.OTHER, 1, Word.Rhyme.ID),
	Word.new("drove", Word.Type.OTHER, 1, Word.Rhyme.OVE),
	Word.new("even", Word.Type.OTHER, 1, Word.Rhyme.EVEN),
	Word.new("ever", Word.Type.OTHER, 1, Word.Rhyme.EVER),
	Word.new("fake", Word.Type.OTHER, 1, Word.Rhyme.AKE),
	Word.new("for", Word.Type.OTHER, 1, Word.Rhyme.OR),
	Word.new("haircut", Word.Type.OTHER, 2, Word.Rhyme.UT),
	Word.new("head", Word.Type.OTHER, 1, Word.Rhyme.ED),
	Word.new("hell,", Word.Type.OTHER, 1, Word.Rhyme.ELL),
	Word.new("here", Word.Type.OTHER, 1, Word.Rhyme.EAR),
	Word.new("in", Word.Type.OTHER, 1, Word.Rhyme.IN),
	Word.new("lamer", Word.Type.OTHER, 2, Word.Rhyme.AMER),
	Word.new("like", Word.Type.OTHER, 1, Word.Rhyme.IKE),
	Word.new("look", Word.Type.OTHER, 1, Word.Rhyme.OOK),
	Word.new("looks", Word.Type.OTHER, 1, Word.Rhyme.OOK),
	Word.new("love", Word.Type.OTHER, 1, Word.Rhyme.UVE),
	Word.new("me", Word.Type.OTHER, 1, Word.Rhyme.EE),
	Word.new("momma", Word.Type.OTHER, 2, Word.Rhyme.AA),
	Word.new("my", Word.Type.OTHER, 1, Word.Rhyme.HY),
	Word.new("of", Word.Type.OTHER, 1, Word.Rhyme.OF),
	Word.new("rather", Word.Type.OTHER, 2, Word.Rhyme.ATHER),
	Word.new("real", Word.Type.OTHER, 1, Word.Rhyme.EAL),
	Word.new("see", Word.Type.OTHER, 1, Word.Rhyme.EE),
	Word.new("seem", Word.Type.OTHER, 1, Word.Rhyme.EEM),
	Word.new("shoes", Word.Type.OTHER, 1, Word.Rhyme.EW),
	Word.new("smarter", Word.Type.OTHER, 2, Word.Rhyme.ARTER),
	Word.new("smell", Word.Type.OTHER, 1, Word.Rhyme.ELL),
	Word.new("so", Word.Type.OTHER, 1, Word.Rhyme.O),
	Word.new("stupider", Word.Type.OTHER, 3, Word.Rhyme.UPIDER),
	Word.new("take", Word.Type.OTHER, 1, Word.Rhyme.AKE),
	Word.new("taking", Word.Type.OTHER, 2, Word.Rhyme.AKING),
	Word.new("than", Word.Type.OTHER, 1, Word.Rhyme.AN),
	Word.new("the", Word.Type.OTHER, 1, Word.Rhyme.UH),
	Word.new("those", Word.Type.OTHER, 1, Word.Rhyme.OSE),
	Word.new("you'll", Word.Type.OTHER, 1, Word.Rhyme.ULL),
	Word.new("your", Word.Type.OTHER, 1, Word.Rhyme.OUR),
	Word.new("by", Word.Type.OTHER, 1, Word.Rhyme.HY),
	Word.new("brain", Word.Type.NOUN, 1, Word.Rhyme.AIN, Word.Sounds.b, Word.Vowel.aɪ),
	Word.new("truck", Word.Type.NOUN, 1, Word.Rhyme.UCK),
	Word.new("duck", Word.Type.NOUN, 1),
	Word.new("brick", Word.Type.NOUN, 1),
	Word.new("fish", Word.Type.NOUN, 1),
	Word.new("garbage", Word.Type.NOUN, 2),
	Word.new("dumpster", Word.Type.NOUN, 2),
	Word.new("cheese", Word.Type.NOUN, 1),
	Word.new("L", Word.Type.NOUN, 1),
	Word.new("you", Word.Type.NOUN, 1),
	Word.new("anyone", Word.Type.NOUN, 2),
	Word.new("loser", Word.Type.NOUN, 2),
	Word.new("winner", Word.Type.NOUN, 2),
	Word.new("dinner", Word.Type.NOUN, 2),
	Word.new("chicken", Word.Type.NOUN, 2),
	Word.new("potato", Word.Type.NOUN, 3),
	Word.new("tomato", Word.Type.NOUN, 3),
	Word.new("water", Word.Type.NOUN, 2),
	Word.new("father", Word.Type.NOUN, 2),
	Word.new("mother", Word.Type.NOUN, 2),
	Word.new("sister", Word.Type.NOUN, 2),
	Word.new("brother", Word.Type.NOUN, 2),
	Word.new("fool", Word.Type.NOUN, 1),
	Word.new("school", Word.Type.NOUN, 1),
	Word.new("tool", Word.Type.NOUN, 1),
	Word.new("bars", Word.Type.NOUN, 1),
	Word.new("cars", Word.Type.NOUN, 1),
	Word.new("flows", Word.Type.NOUN, 1),
	Word.new("lyrics", Word.Type.NOUN, 2),
	Word.new("Rhymes", Word.Type.NOUN, 1),
	Word.new("songs", Word.Type.NOUN, 1),
	Word.new("verses", Word.Type.NOUN, 2),
	Word.new("fan", Word.Type.NOUN, 1),
	Word.new("dog", Word.Type.NOUN, 1),
	Word.new("cat", Word.Type.NOUN, 1),
	Word.new("rat", Word.Type.NOUN, 1),
	Word.new("bat", Word.Type.NOUN, 1),
	Word.new("gun", Word.Type.NOUN, 1),
	Word.new("knife", Word.Type.NOUN, 1),
	Word.new("ball", Word.Type.NOUN, 1),
	Word.new("pizza", Word.Type.NOUN, 2),
	Word.new("soda", Word.Type.NOUN, 2),
	Word.new("burger", Word.Type.NOUN, 2),
	Word.new("toaster", Word.Type.NOUN, 2),
	Word.new("blender", Word.Type.NOUN, 2),
	Word.new("microwave", Word.Type.NOUN, 3),
	Word.new("fridge", Word.Type.NOUN, 1),
	Word.new("keyboard", Word.Type.NOUN, 2),
	Word.new("pen", Word.Type.NOUN, 1),
	Word.new("pencil", Word.Type.NOUN, 1),
	Word.new("plane", Word.Type.NOUN, 1),
	Word.new("jet", Word.Type.NOUN, 1),
	Word.new("run", Word.Type.VERB, 1),
	Word.new("walk", Word.Type.VERB, 1),
	Word.new("rap", Word.Type.VERB, 1),
	Word.new("bounce", Word.Type.VERB, 1),
	Word.new("play", Word.Type.VERB, 1),
	Word.new("eat", Word.Type.VERB, 1),
	Word.new("drink", Word.Type.VERB, 1),
	Word.new("poop", Word.Type.VERB, 1),
	Word.new("pee", Word.Type.VERB, 1),
	Word.new("learn", Word.Type.VERB, 1),
	Word.new("sing", Word.Type.VERB, 1),
	Word.new("write", Word.Type.VERB, 1),
	Word.new("love", Word.Type.VERB, 1),
	Word.new("hate", Word.Type.VERB, 1),
	Word.new("trash", Word.Type.VERB, 1),
	Word.new("rapping", Word.Type.VERB, 2),
	Word.new("writing", Word.Type.VERB, 2),
	Word.new("winning", Word.Type.VERB, 2),
	Word.new("losing", Word.Type.VERB, 2),
	Word.new("balling", Word.Type.VERB, 2),
	Word.new("pooping", Word.Type.VERB, 2),
	Word.new("peeing", Word.Type.VERB, 2),
	Word.new("singing", Word.Type.VERB, 2),
	Word.new("eating", Word.Type.VERB, 2),
	Word.new("drinking", Word.Type.VERB, 2),
	Word.new("loving", Word.Type.VERB, 2),
	Word.new("hating", Word.Type.VERB, 2),
	Word.new("stinky", Word.Type.ADJECTIVE, 2),
	Word.new("smelly", Word.Type.ADJECTIVE, 2),
	Word.new("awesome", Word.Type.ADJECTIVE, 2),
	Word.new("greatest", Word.Type.ADJECTIVE, 2),
	Word.new("lamest", Word.Type.ADJECTIVE, 2),
	Word.new("great", Word.Type.ADJECTIVE, 1),
	Word.new("lame", Word.Type.ADJECTIVE, 1),
	Word.new("stupid", Word.Type.ADJECTIVE, 2),
	Word.new("smoked", Word.Type.ADJECTIVE, 1),
	Word.new("silly", Word.Type.ADJECTIVE, 2),
	Word.new("simple", Word.Type.ADJECTIVE, 1),
	Word.new("crazy", Word.Type.ADJECTIVE, 2),
	Word.new("amazing", Word.Type.ADJECTIVE, 2),
	Word.new("spooky", Word.Type.ADJECTIVE, 2),
	Word.new("funny", Word.Type.ADJECTIVE, 2),
	Word.new("awful", Word.Type.ADJECTIVE, 2),
	Word.new("terrible", Word.Type.ADJECTIVE, 3),
	Word.new("bad", Word.Type.ADJECTIVE, 1),
	Word.new("good", Word.Type.ADJECTIVE, 1),
	Word.new("so-so", Word.Type.ADJECTIVE, 2),
	Word.new("shocking", Word.Type.ADJECTIVE, 2),
	Word.new("confusing", Word.Type.ADJECTIVE, 3),
	Word.new("mediocre", Word.Type.ADJECTIVE, 4),
	Word.new("mid", Word.Type.ADJECTIVE, 1),
]

var phrase_set : Array[Phrase] = [
	Phrase.new("you look like a %s", [Blank.new(2)]),
	Phrase.new("you smell like a %s", [Blank.new(2)]),
	Phrase.new("i'd rather be %s", [Blank.new(1)]),
	Phrase.new("you're taking the %s", [Blank.new(1)]),
	Phrase.new("i'm better than %s", [Blank.new(2)]),
	Phrase.new("i'm cooler than %s", [Blank.new(2)]),
	Phrase.new("you're lamer than %s", [Blank.new(1)]),
	Phrase.new("i'm smarter than %s", [Blank.new(1)]),
	Phrase.new("you're stupider than %s", [Blank.new(1)]),
	Phrase.new("where did you %s ?", [Blank.new(1)]),
	Phrase.new("why are you %s ?", [Blank.new(1)]),
	Phrase.new("stop being %s", [Blank.new(2)]),
	Phrase.new("i'll %s you for real", [Blank.new(1)]),
	Phrase.new("you cannot %s me", [Blank.new(1)]),
	Phrase.new("take a %s %s", [Blank.new(1), Blank.new(1)]),
	Phrase.new("you are %s %s", [Blank.new(2), Blank.new(2)]),
	Phrase.new("you look like my %s", [Blank.new(1)]),
	Phrase.new("your momma so %s", [Blank.new(1)]),
	Phrase.new("%s", [Blank.new(2)]),
	Phrase.new("and those shoes ? %s", [Blank.new(2)]),
	Phrase.new("only %s could be your fan", [Blank.new(1)]),
	Phrase.new("you can't even %s", [Blank.new(1)]),
	Phrase.new("you couldn't even afford %s", [Blank.new(1)]),
	Phrase.new("you seem like a love child born of %s", [Blank.new(2)]),
	Phrase.new("i see you drove here in a %s", [Blank.new(2)]),
	Phrase.new("you're fake as hell you'll only ever be a %s", [Blank.new(1)]),
	Phrase.new("you %s like a %s", [Blank.new(1), Blank.new(1)]),
]

var word_set : Array[StringName] = [
	"brain",
	"simple",
	"smoked",
	"truck",
	"duck",
	"brick",
	"Fish",
	"Garbage",
	"Dumpster",
	"Cheese",
	"L",
	"You",
	"Me",
	"Anyone",
	"Loser",
	"Winner",
	"Dinner",
	"Chicken",
	"Potato",
	"Tomato",
	"Water",
	"Father",
	"Mother",
	"Sister",
	"Brother",
	"Fool",
	"School",
	"Tool",
	"Bars",
	"Cars",
	"Flows",
	"Rhymes",
	"Lyrics",
	"Songs",
	"Verses",
	"Dog",
	"Cat",
	"Rat",
	"Gun",
	"Bat",
	"Knife",
	"Ball",
	"Pizza",
	"Soda",
	"Burger",
	"Toaster",
	"Blender",
	"Microwave",
	"Fridge",
	"Keyboard",
	"Pen",
	"Pencil",
	"Run",
	"Walk",
	"Rap",
	"Bounce",
	"Play",
	"Eat",
	"Drink",
	"Poop",
	"Pee",
	"Learn",
	"Sing",
	"Write",
	"Love",
	"Hate",
	"Trash",
	"Plane",
	"Jet",
	"Rapping",
	"Writing",
	"Winning",
	"Losing",
	"Balling",
	"Pooping",
	"Peeing",
	"Singing",
	"Eating",
	"Drinking",
	"Loving",
	"Hating",
	"Stinky",
	"Smelly",
	"Awesome",
	"Greatest",
	"Lamest",
	"Great",
	"Lame",
	"Stupid",
	"Silly",
	"Crazy",
	"Amazing",
	"Spooky",
	"Funny",
	"Awful",
	"Terrible",
	"Bad",
	"Good",
	"Shocking",
	"Confusing",
	"Mediocre",
	"So-so",
	"Mid",
]


func _ready() -> void:
	var dict = DictData.new(words)
	ResourceSaver.save(dict, "res://data/dictionary.tres")
	# var phrase_data = PhraseSet.new(phrase_set)
	# ResourceSaver.save(phrase_data, "res://data/base_phrases.tres")
	# var word_data = WordSet.new(word_set)
	# ResourceSaver.save(word_data, "res://data/base_words.tres")
