class_name WordData
extends RefCounted

static var phrase_words : Array[Word] = [
	Word.new("and", Word.Type.NONE, 1, Word.Rhyme.AH0_N_D, Word.Sounds.AH, Word.Vowels.AH, Word.Group.NONE),
	Word.new("are", Word.Type.NONE, 1, Word.Rhyme.AA1_R, Word.Sounds.AA, Word.Vowels.AA, Word.Group.NONE),
	Word.new("bet", Word.Type.NONE, 1, Word.Rhyme.EH1_T, Word.Sounds.B, Word.Vowels.EH, Word.Group.NONE),
	Word.new("don't", Word.Type.NONE, 1, Word.Rhyme.OW1_N_T, Word.Sounds.D, Word.Vowels.OW, Word.Group.NONE),
	Word.new("drink", Word.Type.NONE, 1, Word.Rhyme.IH1_NG_K, Word.Sounds.D, Word.Vowels.IH, Word.Group.NONE),
	Word.new("eat", Word.Type.NONE, 1, Word.Rhyme.IY1_T, Word.Sounds.IY, Word.Vowels.IY, Word.Group.NONE),
	Word.new("i", Word.Type.NONE, 1, Word.Rhyme.AY1, Word.Sounds.AY, Word.Vowels.AY, Word.Group.NONE),
	Word.new("i'd", Word.Type.NONE, 1, Word.Rhyme.AY1_D, Word.Sounds.AY, Word.Vowels.AY, Word.Group.NONE),
	Word.new("i'll", Word.Type.NONE, 1, Word.Rhyme.AY1_L, Word.Sounds.AY, Word.Vowels.AY, Word.Group.NONE),
	Word.new("i'm", Word.Type.NONE, 1, Word.Rhyme.AY1_M, Word.Sounds.AY, Word.Vowels.AY, Word.Group.NONE),
	Word.new("if", Word.Type.NONE, 1, Word.Rhyme.IH1_F, Word.Sounds.IH, Word.Vowels.IH, Word.Group.NONE),
	Word.new("keep", Word.Type.NONE, 1, Word.Rhyme.IY1_P, Word.Sounds.K, Word.Vowels.IY, Word.Group.NONE),
	Word.new("no", Word.Type.NONE, 1, Word.Rhyme.OW1, Word.Sounds.N, Word.Vowels.OW, Word.Group.NONE),
	Word.new("on", Word.Type.NONE, 1, Word.Rhyme.AA1_N, Word.Sounds.AA, Word.Vowels.AA, Word.Group.NONE),
	Word.new("only", Word.Type.NONE, 2, Word.Rhyme.OW1_N_L_IY0, Word.Sounds.OW, Word.Vowels.OW, Word.Group.NONE),
	Word.new("so", Word.Type.NONE, 1, Word.Rhyme.OW1, Word.Sounds.S, Word.Vowels.OW, Word.Group.NONE),
	Word.new("stop", Word.Type.NONE, 1, Word.Rhyme.AA1_P, Word.Sounds.S, Word.Vowels.AA, Word.Group.NONE),
	Word.new("take", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.T, Word.Vowels.EY, Word.Group.NONE),
	Word.new("the", Word.Type.NONE, 1, Word.Rhyme.DH_AH0, Word.Sounds.DH, Word.Vowels.AH, Word.Group.NONE),
	Word.new("where", Word.Type.NONE, 1, Word.Rhyme.EH1_R, Word.Sounds.W, Word.Vowels.EH, Word.Group.NONE),
	Word.new("why", Word.Type.NONE, 1, Word.Rhyme.AY1, Word.Sounds.W, Word.Vowels.AY, Word.Group.NONE),
	Word.new("you", Word.Type.NONE, 1, Word.Rhyme.UW1, Word.Sounds.Y, Word.Vowels.UW, Word.Group.NONE),
	Word.new("you'll", Word.Type.NONE, 1, Word.Rhyme.UW1_L, Word.Sounds.Y, Word.Vowels.UW, Word.Group.NONE),
	Word.new("you're", Word.Type.NONE, 1, Word.Rhyme.UH1_R, Word.Sounds.Y, Word.Vowels.UH, Word.Group.NONE),
	Word.new("your", Word.Type.NONE, 1, Word.Rhyme.AO1_R, Word.Sounds.Y, Word.Vowels.AO, Word.Group.NONE),
	Word.new("a", Word.Type.NONE, 1, Word.Rhyme.AH0, Word.Sounds.AH, Word.Vowels.AH, Word.Group.NONE),
	Word.new("afford", Word.Type.NONE, 2, Word.Rhyme.AO1_R_D, Word.Sounds.AH, Word.Vowels.AO, Word.Group.NONE),
	Word.new("all", Word.Type.NONE, 1, Word.Rhyme.AO1_L, Word.Sounds.AO, Word.Vowels.AO, Word.Group.NONE),
	Word.new("always", Word.Type.NONE, 2, Word.Rhyme.AO1_L_W_EY2_Z, Word.Sounds.AO, Word.Vowels.AO, Word.Group.NONE),
	Word.new("and", Word.Type.NONE, 1, Word.Rhyme.AH0_N_D, Word.Sounds.AH, Word.Vowels.AH, Word.Group.NONE),
	Word.new("anymore", Word.Type.NONE, 3, Word.Rhyme.AO1_R, Word.Sounds.EH, Word.Vowels.AO, Word.Group.NONE),
	Word.new("are", Word.Type.NONE, 1, Word.Rhyme.AA1_R, Word.Sounds.AA, Word.Vowels.AA, Word.Group.NONE),
	Word.new("as", Word.Type.NONE, 1, Word.Rhyme.AE1_Z, Word.Sounds.AE, Word.Vowels.AE, Word.Group.NONE),
	Word.new("at", Word.Type.NONE, 1, Word.Rhyme.AE1_T, Word.Sounds.AE, Word.Vowels.AE, Word.Group.NONE),
	Word.new("be", Word.Type.NONE, 1, Word.Rhyme.IY1, Word.Sounds.B, Word.Vowels.IY, Word.Group.NONE),
	Word.new("being", Word.Type.NONE, 2, Word.Rhyme.IY1_IH0_NG, Word.Sounds.B, Word.Vowels.IY, Word.Group.NONE),
	Word.new("better", Word.Type.NONE, 2, Word.Rhyme.EH1_T_ER0, Word.Sounds.B, Word.Vowels.EH, Word.Group.NONE),
	Word.new("born", Word.Type.NONE, 1, Word.Rhyme.AO1_R_N, Word.Sounds.B, Word.Vowels.AO, Word.Group.NONE),
	Word.new("broke", Word.Type.NONE, 1, Word.Rhyme.OW1_K, Word.Sounds.B, Word.Vowels.OW, Word.Group.NONE),
	Word.new("call", Word.Type.NONE, 1, Word.Rhyme.AO1_L, Word.Sounds.K, Word.Vowels.AO, Word.Group.NONE),
	Word.new("can't", Word.Type.NONE, 1, Word.Rhyme.AE1_N_T, Word.Sounds.K, Word.Vowels.AE, Word.Group.NONE),
	Word.new("cannot", Word.Type.NONE, 2, Word.Rhyme.AE1_N_AA0_T, Word.Sounds.K, Word.Vowels.AE, Word.Group.NONE),
	Word.new("child", Word.Type.NONE, 1, Word.Rhyme.AY1_L_D, Word.Sounds.CH, Word.Vowels.AY, Word.Group.NONE),
	Word.new("cooler", Word.Type.NONE, 2, Word.Rhyme.UW1_L_ER0, Word.Sounds.K, Word.Vowels.UW, Word.Group.NONE),
	Word.new("could", Word.Type.NONE, 1, Word.Rhyme.UH1_D, Word.Sounds.K, Word.Vowels.UH, Word.Group.NONE),
	Word.new("couldn't", Word.Type.NONE, 2, Word.Rhyme.UH1_D_AH0_N_T, Word.Sounds.K, Word.Vowels.UH, Word.Group.NONE),
	Word.new("did", Word.Type.NONE, 1, Word.Rhyme.IH1_D, Word.Sounds.D, Word.Vowels.IH, Word.Group.NONE),
	Word.new("die", Word.Type.NONE, 1, Word.Rhyme.AY1, Word.Sounds.D, Word.Vowels.AY, Word.Group.NONE),
	Word.new("do", Word.Type.NONE, 1, Word.Rhyme.UW1, Word.Sounds.D, Word.Vowels.UW, Word.Group.NONE),
	Word.new("don't", Word.Type.NONE, 1, Word.Rhyme.OW1_N_T, Word.Sounds.D, Word.Vowels.OW, Word.Group.NONE),
	Word.new("drove", Word.Type.NONE, 1, Word.Rhyme.OW1_V, Word.Sounds.D, Word.Vowels.OW, Word.Group.NONE),
	Word.new("end", Word.Type.NONE, 1, Word.Rhyme.EH1_N_D, Word.Sounds.EH, Word.Vowels.EH, Word.Group.NONE),
	Word.new("even", Word.Type.NONE, 2, Word.Rhyme.IY1_V_IH0_N, Word.Sounds.IY, Word.Vowels.IY, Word.Group.NONE),
	Word.new("ever", Word.Type.NONE, 2, Word.Rhyme.EH1_V_ER0, Word.Sounds.EH, Word.Vowels.EH, Word.Group.NONE),
	Word.new("fake", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.F, Word.Vowels.EY, Word.Group.NONE),
	Word.new("fan", Word.Type.NONE, 1, Word.Rhyme.AE1_N, Word.Sounds.F, Word.Vowels.AE, Word.Group.NONE),
	Word.new("for", Word.Type.NONE, 1, Word.Rhyme.AO1_R, Word.Sounds.F, Word.Vowels.AO, Word.Group.NONE),
	Word.new("give", Word.Type.NONE, 1, Word.Rhyme.IH1_V, Word.Sounds.G, Word.Vowels.IH, Word.Group.NONE),
	Word.new("goons", Word.Type.NONE, 1, Word.Rhyme.UW1_N_Z, Word.Sounds.G, Word.Vowels.UW, Word.Group.NONE),
	Word.new("had", Word.Type.NONE, 1, Word.Rhyme.AE1_D, Word.Sounds.HH, Word.Vowels.AE, Word.Group.NONE),
	Word.new("haircut", Word.Type.NONE, 2, Word.Rhyme.EH1_R_K_AH2_T, Word.Sounds.HH, Word.Vowels.EH, Word.Group.NONE),
	Word.new("have", Word.Type.NONE, 1, Word.Rhyme.AE1_V, Word.Sounds.HH, Word.Vowels.AE, Word.Group.NONE),
	Word.new("head", Word.Type.NONE, 1, Word.Rhyme.EH1_D, Word.Sounds.HH, Word.Vowels.EH, Word.Group.NONE),
	Word.new("hell", Word.Type.NONE, 1, Word.Rhyme.EH1_L, Word.Sounds.HH, Word.Vowels.EH, Word.Group.NONE),
	Word.new("here", Word.Type.NONE, 1, Word.Rhyme.IY1_R, Word.Sounds.HH, Word.Vowels.IY, Word.Group.NONE),
	Word.new("human", Word.Type.NONE, 2, Word.Rhyme.UW1_M_AH0_N, Word.Sounds.HH, Word.Vowels.UW, Word.Group.NONE),
	Word.new("in", Word.Type.NONE, 1, Word.Rhyme.IH0_N, Word.Sounds.IH, Word.Vowels.IH, Word.Group.NONE),
	Word.new("is", Word.Type.NONE, 1, Word.Rhyme.IH1_Z, Word.Sounds.IH, Word.Vowels.IH, Word.Group.NONE),
	Word.new("it", Word.Type.NONE, 1, Word.Rhyme.IH1_T, Word.Sounds.IH, Word.Vowels.IH, Word.Group.NONE),
	Word.new("lamer", Word.Type.NONE, 2, Word.Rhyme.EY1_M_ER0, Word.Sounds.L, Word.Vowels.EY, Word.Group.NONE),
	Word.new("least", Word.Type.NONE, 1, Word.Rhyme.IY1_S_T, Word.Sounds.L, Word.Vowels.IY, Word.Group.NONE),
	Word.new("like", Word.Type.NONE, 1, Word.Rhyme.AY1_K, Word.Sounds.L, Word.Vowels.AY, Word.Group.NONE),
	Word.new("look", Word.Type.NONE, 1, Word.Rhyme.UH1_K, Word.Sounds.L, Word.Vowels.UH, Word.Group.NONE),
	Word.new("looks", Word.Type.NONE, 1, Word.Rhyme.UH1_K_S, Word.Sounds.L, Word.Vowels.UH, Word.Group.NONE),
	Word.new("love", Word.Type.NONE, 1, Word.Rhyme.AH1_V, Word.Sounds.L, Word.Vowels.AH, Word.Group.NONE),
	Word.new("lyrical", Word.Type.NONE, 3, Word.Rhyme.IH1_R_IH0_K_AH0_L, Word.Sounds.L, Word.Vowels.IH, Word.Group.NONE),
	Word.new("make", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.M, Word.Vowels.EY, Word.Group.NONE),
	Word.new("me", Word.Type.NONE, 1, Word.Rhyme.IY1, Word.Sounds.M, Word.Vowels.IY, Word.Group.NONE),
	Word.new("momma", Word.Type.NONE, 2, Word.Rhyme.AA1_M_AH0, Word.Sounds.M, Word.Vowels.AA, Word.Group.NONE),
	Word.new("my", Word.Type.NONE, 1, Word.Rhyme.AY1, Word.Sounds.M, Word.Vowels.AY, Word.Group.NONE),
	Word.new("never", Word.Type.NONE, 2, Word.Rhyme.EH1_V_ER0, Word.Sounds.N, Word.Vowels.EH, Word.Group.NONE),
	Word.new("of", Word.Type.NONE, 1, Word.Rhyme.AH1_V, Word.Sounds.AH, Word.Vowels.AH, Word.Group.NONE),
	Word.new("only", Word.Type.NONE, 2, Word.Rhyme.OW1_N_L_IY0, Word.Sounds.OW, Word.Vowels.OW, Word.Group.NONE),
	Word.new("put", Word.Type.NONE, 1, Word.Rhyme.UH1_T, Word.Sounds.P, Word.Vowels.UH, Word.Group.NONE),
	Word.new("rather", Word.Type.NONE, 2, Word.Rhyme.AE1_DH_ER0, Word.Sounds.R, Word.Vowels.AE, Word.Group.NONE),
	Word.new("real", Word.Type.NONE, 1, Word.Rhyme.IY1_L, Word.Sounds.R, Word.Vowels.IY, Word.Group.NONE),
	Word.new("scared", Word.Type.NONE, 1, Word.Rhyme.EH1_R_D, Word.Sounds.S, Word.Vowels.EH, Word.Group.NONE),
	Word.new("see", Word.Type.NONE, 1, Word.Rhyme.IY1, Word.Sounds.S, Word.Vowels.IY, Word.Group.NONE),
	Word.new("seem", Word.Type.NONE, 1, Word.Rhyme.IY1_M, Word.Sounds.S, Word.Vowels.IY, Word.Group.NONE),
	Word.new("shoes", Word.Type.NONE, 1, Word.Rhyme.UW1_Z, Word.Sounds.SH, Word.Vowels.UW, Word.Group.NONE),
	Word.new("smarter", Word.Type.NONE, 2, Word.Rhyme.AA1_R_T_ER0, Word.Sounds.S, Word.Vowels.AA, Word.Group.NONE),
	Word.new("smell", Word.Type.NONE, 1, Word.Rhyme.EH1_L, Word.Sounds.S, Word.Vowels.EH, Word.Group.NONE),
	Word.new("so", Word.Type.NONE, 1, Word.Rhyme.OW1, Word.Sounds.S, Word.Vowels.OW, Word.Group.NONE),
	Word.new("take", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.T, Word.Vowels.EY, Word.Group.NONE),
	Word.new("taking", Word.Type.NONE, 2, Word.Rhyme.EY1_K_IH0_NG, Word.Sounds.T, Word.Vowels.EY, Word.Group.NONE),
	Word.new("than", Word.Type.NONE, 1, Word.Rhyme.AE1_N, Word.Sounds.DH, Word.Vowels.AE, Word.Group.NONE),
	Word.new("the", Word.Type.NONE, 1, Word.Rhyme.DH_AH0, Word.Sounds.DH, Word.Vowels.AH, Word.Group.NONE),
	Word.new("they", Word.Type.NONE, 1, Word.Rhyme.EY1, Word.Sounds.DH, Word.Vowels.EY, Word.Group.NONE),
	Word.new("they'd", Word.Type.NONE, 1, Word.Rhyme.EY1_D, Word.Sounds.DH, Word.Vowels.EY, Word.Group.NONE),
	Word.new("this", Word.Type.NONE, 1, Word.Rhyme.IH1_S, Word.Sounds.DH, Word.Vowels.IH, Word.Group.NONE),
	Word.new("those", Word.Type.NONE, 1, Word.Rhyme.OW1_Z, Word.Sounds.DH, Word.Vowels.OW, Word.Group.NONE),
	Word.new("thought", Word.Type.NONE, 1, Word.Rhyme.AO1_T, Word.Sounds.TH, Word.Vowels.AO, Word.Group.NONE),
	Word.new("to", Word.Type.NONE, 1, Word.Rhyme.UW1, Word.Sounds.T, Word.Vowels.UW, Word.Group.NONE),
	Word.new("tomb", Word.Type.NONE, 1, Word.Rhyme.UW1_M, Word.Sounds.T, Word.Vowels.UW, Word.Group.NONE),
	Word.new("up", Word.Type.NONE, 1, Word.Rhyme.AH1_P, Word.Sounds.AH, Word.Vowels.AH, Word.Group.NONE),
	Word.new("version", Word.Type.NONE, 2, Word.Rhyme.ER1_ZH_AH0_N, Word.Sounds.V, Word.Vowels.ER, Word.Group.NONE),
	Word.new("wanna", Word.Type.NONE, 2, Word.Rhyme.AA1_N_AH0, Word.Sounds.W, Word.Vowels.AA, Word.Group.NONE),
	Word.new("want", Word.Type.NONE, 1, Word.Rhyme.AA1_N_T, Word.Sounds.W, Word.Vowels.AA, Word.Group.NONE),
	Word.new("with", Word.Type.NONE, 1, Word.Rhyme.IH1_DH, Word.Sounds.W, Word.Vowels.IH, Word.Group.NONE),
	Word.new("won't", Word.Type.NONE, 1, Word.Rhyme.OW1_N_T, Word.Sounds.W, Word.Vowels.OW, Word.Group.NONE),
	Word.new("write", Word.Type.NONE, 1, Word.Rhyme.AY1_T, Word.Sounds.R, Word.Vowels.AY, Word.Group.NONE),
	Word.new("you", Word.Type.NONE, 1, Word.Rhyme.UW1, Word.Sounds.Y, Word.Vowels.UW, Word.Group.NONE),
	Word.new("you'd", Word.Type.NONE, 1, Word.Rhyme.UW1_D, Word.Sounds.Y, Word.Vowels.UW, Word.Group.NONE),
	Word.new("you'll", Word.Type.NONE, 1, Word.Rhyme.UW1_L, Word.Sounds.Y, Word.Vowels.UW, Word.Group.NONE),
	Word.new("you're", Word.Type.NONE, 1, Word.Rhyme.UH1_R, Word.Sounds.Y, Word.Vowels.UH, Word.Group.NONE),
	Word.new("your", Word.Type.NONE, 1, Word.Rhyme.AO1_R, Word.Sounds.Y, Word.Vowels.AO, Word.Group.NONE),
]

static var phrase_words_manual : Array[Word] = [
	Word.new("paparazzi'd", Word.Type.NONE, 4, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("stupider", Word.Type.NONE, 4, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
]

# TODO:
"""
paparazzi'd
stupider
"""

static var player_words : Array[Word] = [
	Word.new("affinity", Word.Type.NONE, 4, Word.Rhyme.IH1_N_AH0_T_IY0, Word.Sounds.AH, Word.Vowels.IH, Word.Group.NONE),
	Word.new("amazing", Word.Type.NONE, 3, Word.Rhyme.EY1_Z_IH0_NG, Word.Sounds.AH, Word.Vowels.EY, Word.Group.NONE),
	Word.new("ant", Word.Type.NONE, 1, Word.Rhyme.AE1_N_T, Word.Sounds.AE, Word.Vowels.AE, Word.Group.NONE),
	Word.new("anyone", Word.Type.NONE, 3, Word.Rhyme.EH1_N_IY0_W_AH2_N, Word.Sounds.EH, Word.Vowels.EH, Word.Group.NONE),
	Word.new("awesome", Word.Type.NONE, 2, Word.Rhyme.AA1_S_AH0_M, Word.Sounds.AA, Word.Vowels.AA, Word.Group.NONE),
	Word.new("awful", Word.Type.NONE, 2, Word.Rhyme.AA1_F_AH0_L, Word.Sounds.AA, Word.Vowels.AA, Word.Group.NONE),
	Word.new("bad", Word.Type.NONE, 1, Word.Rhyme.AE1_D, Word.Sounds.B, Word.Vowels.AE, Word.Group.NONE),
	Word.new("ball", Word.Type.NONE, 1, Word.Rhyme.AO1_L, Word.Sounds.B, Word.Vowels.AO, Word.Group.NONE),
	Word.new("balling", Word.Type.NONE, 2, Word.Rhyme.AO1_L_IH0_NG, Word.Sounds.B, Word.Vowels.AO, Word.Group.NONE),
	Word.new("ban", Word.Type.NONE, 1, Word.Rhyme.AE1_N, Word.Sounds.B, Word.Vowels.AE, Word.Group.NONE),
	Word.new("band", Word.Type.NONE, 1, Word.Rhyme.AE1_N_D, Word.Sounds.B, Word.Vowels.AE, Word.Group.NONE),
	Word.new("bars", Word.Type.NONE, 1, Word.Rhyme.AA1_R_Z, Word.Sounds.B, Word.Vowels.AA, Word.Group.NONE),
	Word.new("base", Word.Type.NONE, 1, Word.Rhyme.EY1_S, Word.Sounds.B, Word.Vowels.EY, Word.Group.NONE),
	Word.new("bat", Word.Type.NONE, 1, Word.Rhyme.AE1_T, Word.Sounds.B, Word.Vowels.AE, Word.Group.NONE),
	Word.new("bed", Word.Type.NONE, 1, Word.Rhyme.EH1_D, Word.Sounds.B, Word.Vowels.EH, Word.Group.NONE),
	Word.new("beer", Word.Type.NONE, 1, Word.Rhyme.IH1_R, Word.Sounds.B, Word.Vowels.IH, Word.Group.NONE),
	Word.new("biting", Word.Type.NONE, 2, Word.Rhyme.AY1_T_IH0_NG, Word.Sounds.B, Word.Vowels.AY, Word.Group.NONE),
	Word.new("blender", Word.Type.NONE, 2, Word.Rhyme.EH1_N_D_ER0, Word.Sounds.B, Word.Vowels.EH, Word.Group.NONE),
	Word.new("blossom", Word.Type.NONE, 2, Word.Rhyme.AA1_S_AH0_M, Word.Sounds.B, Word.Vowels.AA, Word.Group.NONE),
	Word.new("blues", Word.Type.NONE, 1, Word.Rhyme.UW1_Z, Word.Sounds.B, Word.Vowels.UW, Word.Group.NONE),
	Word.new("boos", Word.Type.NONE, 1, Word.Rhyme.UW1_Z, Word.Sounds.B, Word.Vowels.UW, Word.Group.NONE),
	Word.new("bounce", Word.Type.NONE, 1, Word.Rhyme.AW1_N_S, Word.Sounds.B, Word.Vowels.AW, Word.Group.NONE),
	Word.new("brick", Word.Type.NONE, 1, Word.Rhyme.IH1_K, Word.Sounds.B, Word.Vowels.IH, Word.Group.NONE),
	Word.new("broke", Word.Type.NONE, 1, Word.Rhyme.OW1_K, Word.Sounds.B, Word.Vowels.OW, Word.Group.NONE),
	Word.new("brother", Word.Type.NONE, 2, Word.Rhyme.AH1_DH_ER0, Word.Sounds.B, Word.Vowels.AH, Word.Group.NONE),
	Word.new("burger", Word.Type.NONE, 2, Word.Rhyme.ER1_G_ER0, Word.Sounds.B, Word.Vowels.ER, Word.Group.NONE),
	Word.new("butt", Word.Type.NONE, 1, Word.Rhyme.AH1_T, Word.Sounds.B, Word.Vowels.AH, Word.Group.NONE),
	Word.new("can", Word.Type.NONE, 1, Word.Rhyme.AE1_N, Word.Sounds.K, Word.Vowels.AE, Word.Group.NONE),
	Word.new("car", Word.Type.NONE, 1, Word.Rhyme.AA1_R, Word.Sounds.K, Word.Vowels.AA, Word.Group.NONE),
	Word.new("case", Word.Type.NONE, 1, Word.Rhyme.EY1_S, Word.Sounds.K, Word.Vowels.EY, Word.Group.NONE),
	Word.new("cat", Word.Type.NONE, 1, Word.Rhyme.AE1_T, Word.Sounds.K, Word.Vowels.AE, Word.Group.NONE),
	Word.new("cell", Word.Type.NONE, 1, Word.Rhyme.EH1_L, Word.Sounds.S, Word.Vowels.EH, Word.Group.NONE),
	Word.new("cheat", Word.Type.NONE, 1, Word.Rhyme.IY1_T, Word.Sounds.CH, Word.Vowels.IY, Word.Group.NONE),
	Word.new("cheese", Word.Type.NONE, 1, Word.Rhyme.IY1_Z, Word.Sounds.CH, Word.Vowels.IY, Word.Group.NONE),
	Word.new("chicken", Word.Type.NONE, 2, Word.Rhyme.IH1_K_AH0_N, Word.Sounds.CH, Word.Vowels.IH, Word.Group.NONE),
	Word.new("coke", Word.Type.NONE, 1, Word.Rhyme.OW1_K, Word.Sounds.K, Word.Vowels.OW, Word.Group.NONE),
	Word.new("confusing", Word.Type.NONE, 3, Word.Rhyme.UW1_Z_IH0_NG, Word.Sounds.K, Word.Vowels.UW, Word.Group.NONE),
	Word.new("control", Word.Type.NONE, 2, Word.Rhyme.OW1_L, Word.Sounds.K, Word.Vowels.OW, Word.Group.NONE),
	Word.new("coups", Word.Type.NONE, 1, Word.Rhyme.UW1_Z, Word.Sounds.K, Word.Vowels.UW, Word.Group.NONE),
	Word.new("crazy", Word.Type.NONE, 2, Word.Rhyme.EY1_Z_IY0, Word.Sounds.K, Word.Vowels.EY, Word.Group.NONE),
	Word.new("crime", Word.Type.NONE, 1, Word.Rhyme.AY1_M, Word.Sounds.K, Word.Vowels.AY, Word.Group.NONE),
	Word.new("criminal", Word.Type.NONE, 3, Word.Rhyme.IH1_M_AH0_N_AH0_L, Word.Sounds.K, Word.Vowels.IH, Word.Group.NONE),
	Word.new("crooks", Word.Type.NONE, 1, Word.Rhyme.UH1_K_S, Word.Sounds.K, Word.Vowels.UH, Word.Group.NONE),
	Word.new("cut", Word.Type.NONE, 1, Word.Rhyme.AH1_T, Word.Sounds.K, Word.Vowels.AH, Word.Group.NONE),
	Word.new("dead", Word.Type.NONE, 1, Word.Rhyme.EH1_D, Word.Sounds.D, Word.Vowels.EH, Word.Group.NONE),
	Word.new("deadbeat", Word.Type.NONE, 2, Word.Rhyme.EH1_D_B_IY2_T, Word.Sounds.D, Word.Vowels.EH, Word.Group.NONE),
	Word.new("dinner", Word.Type.NONE, 2, Word.Rhyme.IH1_N_ER0, Word.Sounds.D, Word.Vowels.IH, Word.Group.NONE),
	Word.new("disclaimer", Word.Type.NONE, 3, Word.Rhyme.EY1_M_ER0, Word.Sounds.D, Word.Vowels.EY, Word.Group.NONE),
	Word.new("divinity", Word.Type.NONE, 4, Word.Rhyme.IH1_N_AH0_T_IY0, Word.Sounds.D, Word.Vowels.IH, Word.Group.NONE),
	Word.new("dog", Word.Type.NONE, 1, Word.Rhyme.AO1_G, Word.Sounds.D, Word.Vowels.AO, Word.Group.NONE),
	Word.new("dove", Word.Type.NONE, 1, Word.Rhyme.AH1_V, Word.Sounds.D, Word.Vowels.AH, Word.Group.NONE),
	Word.new("drama", Word.Type.NONE, 2, Word.Rhyme.AA1_M_AH0, Word.Sounds.D, Word.Vowels.AA, Word.Group.NONE),
	Word.new("dread", Word.Type.NONE, 1, Word.Rhyme.EH1_D, Word.Sounds.D, Word.Vowels.EH, Word.Group.NONE),
	Word.new("drink", Word.Type.NONE, 1, Word.Rhyme.IH1_NG_K, Word.Sounds.D, Word.Vowels.IH, Word.Group.NONE),
	Word.new("drinking", Word.Type.NONE, 2, Word.Rhyme.IH1_NG_K_IH0_NG, Word.Sounds.D, Word.Vowels.IH, Word.Group.NONE),
	Word.new("duck", Word.Type.NONE, 1, Word.Rhyme.AH1_K, Word.Sounds.D, Word.Vowels.AH, Word.Group.NONE),
	Word.new("dumpster", Word.Type.NONE, 2, Word.Rhyme.AH1_M_P_S_T_ER0, Word.Sounds.D, Word.Vowels.AH, Word.Group.NONE),
	Word.new("eat", Word.Type.NONE, 1, Word.Rhyme.IY1_T, Word.Sounds.IY, Word.Vowels.IY, Word.Group.NONE),
	Word.new("eating", Word.Type.NONE, 2, Word.Rhyme.IY1_T_IH0_NG, Word.Sounds.IY, Word.Vowels.IY, Word.Group.NONE),
	Word.new("erase", Word.Type.NONE, 2, Word.Rhyme.EY1_S, Word.Sounds.IH, Word.Vowels.EY, Word.Group.NONE),
	Word.new("face", Word.Type.NONE, 1, Word.Rhyme.EY1_S, Word.Sounds.F, Word.Vowels.EY, Word.Group.NONE),
	Word.new("father", Word.Type.NONE, 2, Word.Rhyme.AA1_DH_ER0, Word.Sounds.F, Word.Vowels.AA, Word.Group.NONE),
	Word.new("fish", Word.Type.NONE, 1, Word.Rhyme.IH1_SH, Word.Sounds.F, Word.Vowels.IH, Word.Group.NONE),
	Word.new("flamer", Word.Type.NONE, 2, Word.Rhyme.EY1_M_ER0, Word.Sounds.F, Word.Vowels.EY, Word.Group.NONE),
	Word.new("flathead", Word.Type.NONE, 2, Word.Rhyme.AE1_T_HH_EH2_D, Word.Sounds.F, Word.Vowels.AE, Word.Group.NONE),
	Word.new("flea", Word.Type.NONE, 1, Word.Rhyme.IY1, Word.Sounds.F, Word.Vowels.IY, Word.Group.NONE),
	Word.new("flee", Word.Type.NONE, 1, Word.Rhyme.IY1, Word.Sounds.F, Word.Vowels.IY, Word.Group.NONE),
	Word.new("flirt", Word.Type.NONE, 1, Word.Rhyme.ER1_T, Word.Sounds.F, Word.Vowels.ER, Word.Group.NONE),
	Word.new("flows", Word.Type.NONE, 1, Word.Rhyme.OW1_Z, Word.Sounds.F, Word.Vowels.OW, Word.Group.NONE),
	Word.new("fool", Word.Type.NONE, 1, Word.Rhyme.UW1_L, Word.Sounds.F, Word.Vowels.UW, Word.Group.NONE),
	Word.new("fridge", Word.Type.NONE, 1, Word.Rhyme.IH1_JH, Word.Sounds.F, Word.Vowels.IH, Word.Group.NONE),
	Word.new("frog", Word.Type.NONE, 1, Word.Rhyme.AA1_G, Word.Sounds.F, Word.Vowels.AA, Word.Group.NONE),
	Word.new("funny", Word.Type.NONE, 2, Word.Rhyme.AH1_N_IY0, Word.Sounds.F, Word.Vowels.AH, Word.Group.NONE),
	Word.new("garbage", Word.Type.NONE, 2, Word.Rhyme.AA1_R_B_IH0_JH, Word.Sounds.G, Word.Vowels.AA, Word.Group.NONE),
	Word.new("gongs", Word.Type.NONE, 1, Word.Rhyme.AO1_NG_Z, Word.Sounds.G, Word.Vowels.AO, Word.Group.NONE),
	Word.new("good", Word.Type.NONE, 1, Word.Rhyme.UH1_D, Word.Sounds.G, Word.Vowels.UH, Word.Group.NONE),
	Word.new("great", Word.Type.NONE, 1, Word.Rhyme.EY1_T, Word.Sounds.G, Word.Vowels.EY, Word.Group.NONE),
	Word.new("greatest", Word.Type.NONE, 2, Word.Rhyme.EY1_T_AH0_S_T, Word.Sounds.G, Word.Vowels.EY, Word.Group.NONE),
	Word.new("greet", Word.Type.NONE, 1, Word.Rhyme.IY1_T, Word.Sounds.G, Word.Vowels.IY, Word.Group.NONE),
	Word.new("gun", Word.Type.NONE, 1, Word.Rhyme.AH1_N, Word.Sounds.G, Word.Vowels.AH, Word.Group.NONE),
	Word.new("hand", Word.Type.NONE, 1, Word.Rhyme.AE1_N_D, Word.Sounds.HH, Word.Vowels.AE, Word.Group.NONE),
	Word.new("hate", Word.Type.NONE, 1, Word.Rhyme.EY1_T, Word.Sounds.HH, Word.Vowels.EY, Word.Group.NONE),
	Word.new("hating", Word.Type.NONE, 2, Word.Rhyme.EY1_T_IH0_NG, Word.Sounds.HH, Word.Vowels.EY, Word.Group.NONE),
	Word.new("hazy", Word.Type.NONE, 2, Word.Rhyme.EY1_Z_IY0, Word.Sounds.HH, Word.Vowels.EY, Word.Group.NONE),
	Word.new("infinity", Word.Type.NONE, 4, Word.Rhyme.IH1_N_AH0_T_IY0, Word.Sounds.IH, Word.Vowels.IH, Word.Group.NONE),
	Word.new("ink", Word.Type.NONE, 1, Word.Rhyme.IH1_NG_K, Word.Sounds.IH, Word.Vowels.IH, Word.Group.NONE),
	Word.new("jet", Word.Type.NONE, 1, Word.Rhyme.EH1_T, Word.Sounds.JH, Word.Vowels.EH, Word.Group.NONE),
	Word.new("joke", Word.Type.NONE, 1, Word.Rhyme.OW1_K, Word.Sounds.JH, Word.Vowels.OW, Word.Group.NONE),
	Word.new("karma", Word.Type.NONE, 2, Word.Rhyme.AA1_R_M_AH0, Word.Sounds.K, Word.Vowels.AA, Word.Group.NONE),
	Word.new("keyboard", Word.Type.NONE, 2, Word.Rhyme.IY1_B_AO2_R_D, Word.Sounds.K, Word.Vowels.IY, Word.Group.NONE),
	Word.new("knife", Word.Type.NONE, 1, Word.Rhyme.AY1_F, Word.Sounds.N, Word.Vowels.AY, Word.Group.NONE),
	Word.new("l", Word.Type.NONE, 1, Word.Rhyme.EH1_L, Word.Sounds.EH, Word.Vowels.EH, Word.Group.NONE),
	Word.new("lame", Word.Type.NONE, 1, Word.Rhyme.EY1_M, Word.Sounds.L, Word.Vowels.EY, Word.Group.NONE),
	Word.new("lazy", Word.Type.NONE, 2, Word.Rhyme.EY1_Z_IY0, Word.Sounds.L, Word.Vowels.EY, Word.Group.NONE),
	Word.new("lead", Word.Type.NONE, 1, Word.Rhyme.EH1_D, Word.Sounds.L, Word.Vowels.EH, Word.Group.NONE),
	Word.new("learn", Word.Type.NONE, 1, Word.Rhyme.ER1_N, Word.Sounds.L, Word.Vowels.ER, Word.Group.NONE),
	Word.new("llama", Word.Type.NONE, 2, Word.Rhyme.AA1_M_AH0, Word.Sounds.L, Word.Vowels.AA, Word.Group.NONE),
	Word.new("loser", Word.Type.NONE, 2, Word.Rhyme.UW1_Z_ER0, Word.Sounds.L, Word.Vowels.UW, Word.Group.NONE),
	Word.new("losing", Word.Type.NONE, 2, Word.Rhyme.UW1_Z_IH0_NG, Word.Sounds.L, Word.Vowels.UW, Word.Group.NONE),
	Word.new("love", Word.Type.NONE, 1, Word.Rhyme.AH1_V, Word.Sounds.L, Word.Vowels.AH, Word.Group.NONE),
	Word.new("loving", Word.Type.NONE, 2, Word.Rhyme.AH1_V_IH0_NG, Word.Sounds.L, Word.Vowels.AH, Word.Group.NONE),
	Word.new("lyrics", Word.Type.NONE, 2, Word.Rhyme.IH1_R_IH0_K_S, Word.Sounds.L, Word.Vowels.IH, Word.Group.NONE),
	Word.new("mace", Word.Type.NONE, 1, Word.Rhyme.EY1_S, Word.Sounds.M, Word.Vowels.EY, Word.Group.NONE),
	Word.new("man", Word.Type.NONE, 1, Word.Rhyme.AE1_N, Word.Sounds.M, Word.Vowels.AE, Word.Group.NONE),
	Word.new("martyr", Word.Type.NONE, 2, Word.Rhyme.AA1_R_T_ER0, Word.Sounds.M, Word.Vowels.AA, Word.Group.NONE),
	Word.new("me", Word.Type.NONE, 1, Word.Rhyme.IY1, Word.Sounds.M, Word.Vowels.IY, Word.Group.NONE),
	Word.new("meal", Word.Type.NONE, 1, Word.Rhyme.IY1_L, Word.Sounds.M, Word.Vowels.IY, Word.Group.NONE),
	Word.new("mediocre", Word.Type.NONE, 4, Word.Rhyme.OW1_K_ER0, Word.Sounds.M, Word.Vowels.OW, Word.Group.NONE),
	Word.new("microwave", Word.Type.NONE, 3, Word.Rhyme.AY1_K_R_AH0_W_EY2_V, Word.Sounds.M, Word.Vowels.AY, Word.Group.NONE),
	Word.new("mid", Word.Type.NONE, 1, Word.Rhyme.IH1_D, Word.Sounds.M, Word.Vowels.IH, Word.Group.NONE),
	Word.new("miracle", Word.Type.NONE, 3, Word.Rhyme.IH1_R_AH0_K_AH0_L, Word.Sounds.M, Word.Vowels.IH, Word.Group.NONE),
	Word.new("monologue", Word.Type.NONE, 3, Word.Rhyme.AA1_N_AH0_L_AO2_G, Word.Sounds.M, Word.Vowels.AA, Word.Group.NONE),
	Word.new("mother", Word.Type.NONE, 2, Word.Rhyme.AH1_DH_ER0, Word.Sounds.M, Word.Vowels.AH, Word.Group.NONE),
	Word.new("mutt", Word.Type.NONE, 1, Word.Rhyme.AH1_T, Word.Sounds.M, Word.Vowels.AH, Word.Group.NONE),
	Word.new("obsolete", Word.Type.NONE, 3, Word.Rhyme.AA1_B_S_AH0_L_IY2_T, Word.Sounds.AA, Word.Vowels.AA, Word.Group.NONE),
	Word.new("orange", Word.Type.NONE, 2, Word.Rhyme.AO1_R_AH0_N_JH, Word.Sounds.AO, Word.Vowels.AO, Word.Group.NONE),
	Word.new("pan", Word.Type.NONE, 1, Word.Rhyme.AE1_N, Word.Sounds.P, Word.Vowels.AE, Word.Group.NONE),
	Word.new("pants", Word.Type.NONE, 1, Word.Rhyme.AE1_N_T_S, Word.Sounds.P, Word.Vowels.AE, Word.Group.NONE),
	Word.new("pea", Word.Type.NONE, 1, Word.Rhyme.IY1, Word.Sounds.P, Word.Vowels.IY, Word.Group.NONE),
	Word.new("pee", Word.Type.NONE, 1, Word.Rhyme.IY1, Word.Sounds.P, Word.Vowels.IY, Word.Group.NONE),
	Word.new("pen", Word.Type.NONE, 1, Word.Rhyme.EH1_N, Word.Sounds.P, Word.Vowels.EH, Word.Group.NONE),
	Word.new("pencil", Word.Type.NONE, 2, Word.Rhyme.EH1_N_S_AH0_L, Word.Sounds.P, Word.Vowels.EH, Word.Group.NONE),
	Word.new("petite", Word.Type.NONE, 2, Word.Rhyme.IY1_T, Word.Sounds.P, Word.Vowels.IY, Word.Group.NONE),
	Word.new("pizza", Word.Type.NONE, 2, Word.Rhyme.IY1_T_S_AH0, Word.Sounds.P, Word.Vowels.IY, Word.Group.NONE),
	Word.new("plane", Word.Type.NONE, 1, Word.Rhyme.EY1_N, Word.Sounds.P, Word.Vowels.EY, Word.Group.NONE),
	Word.new("play", Word.Type.NONE, 1, Word.Rhyme.EY1, Word.Sounds.P, Word.Vowels.EY, Word.Group.NONE),
	Word.new("poke", Word.Type.NONE, 1, Word.Rhyme.OW1_K, Word.Sounds.P, Word.Vowels.OW, Word.Group.NONE),
	Word.new("poop", Word.Type.NONE, 1, Word.Rhyme.UW1_P, Word.Sounds.P, Word.Vowels.UW, Word.Group.NONE),
	Word.new("possum", Word.Type.NONE, 2, Word.Rhyme.AA1_S_AH0_M, Word.Sounds.P, Word.Vowels.AA, Word.Group.NONE),
	Word.new("potato", Word.Type.NONE, 3, Word.Rhyme.EY1_T_OW2, Word.Sounds.P, Word.Vowels.EY, Word.Group.NONE),
	Word.new("prongs", Word.Type.NONE, 1, Word.Rhyme.AO1_NG_Z, Word.Sounds.P, Word.Vowels.AO, Word.Group.NONE),
	Word.new("purple", Word.Type.NONE, 2, Word.Rhyme.ER1_P_AH0_L, Word.Sounds.P, Word.Vowels.ER, Word.Group.NONE),
	Word.new("ran", Word.Type.NONE, 1, Word.Rhyme.AE1_N, Word.Sounds.R, Word.Vowels.AE, Word.Group.NONE),
	Word.new("rap", Word.Type.NONE, 1, Word.Rhyme.AE1_P, Word.Sounds.R, Word.Vowels.AE, Word.Group.NONE),
	Word.new("rapping", Word.Type.NONE, 2, Word.Rhyme.AE1_P_IH0_NG, Word.Sounds.R, Word.Vowels.AE, Word.Group.NONE),
	Word.new("rat", Word.Type.NONE, 1, Word.Rhyme.AE1_T, Word.Sounds.R, Word.Vowels.AE, Word.Group.NONE),
	Word.new("red", Word.Type.NONE, 1, Word.Rhyme.EH1_D, Word.Sounds.R, Word.Vowels.EH, Word.Group.NONE),
	Word.new("rhymes", Word.Type.NONE, 1, Word.Rhyme.AY1_M_Z, Word.Sounds.R, Word.Vowels.AY, Word.Group.NONE),
	Word.new("run", Word.Type.NONE, 1, Word.Rhyme.AH1_N, Word.Sounds.R, Word.Vowels.AH, Word.Group.NONE),
	Word.new("ruse", Word.Type.NONE, 1, Word.Rhyme.UW1_Z, Word.Sounds.R, Word.Vowels.UW, Word.Group.NONE),
	Word.new("silly", Word.Type.NONE, 2, Word.Rhyme.IH1_L_IY0, Word.Sounds.S, Word.Vowels.IH, Word.Group.NONE),
	Word.new("school", Word.Type.NONE, 1, Word.Rhyme.UW1_L, Word.Sounds.S, Word.Vowels.UW, Word.Group.NONE),
	Word.new("shirt", Word.Type.NONE, 1, Word.Rhyme.ER1_T, Word.Sounds.SH, Word.Vowels.ER, Word.Group.NONE),
	Word.new("shocking", Word.Type.NONE, 2, Word.Rhyme.AA1_K_IH0_NG, Word.Sounds.SH, Word.Vowels.AA, Word.Group.NONE),
	Word.new("shove", Word.Type.NONE, 1, Word.Rhyme.AH1_V, Word.Sounds.SH, Word.Vowels.AH, Word.Group.NONE),
	Word.new("sing", Word.Type.NONE, 1, Word.Rhyme.IH1_NG, Word.Sounds.S, Word.Vowels.IH, Word.Group.NONE),
	Word.new("singing", Word.Type.NONE, 2, Word.Rhyme.IH1_NG_IH0_NG, Word.Sounds.S, Word.Vowels.IH, Word.Group.NONE),
	Word.new("sister", Word.Type.NONE, 2, Word.Rhyme.IH1_S_T_ER0, Word.Sounds.S, Word.Vowels.IH, Word.Group.NONE),
	Word.new("skirt", Word.Type.NONE, 1, Word.Rhyme.ER1_T, Word.Sounds.S, Word.Vowels.ER, Word.Group.NONE),
	Word.new("slog", Word.Type.NONE, 1, Word.Rhyme.AA1_G, Word.Sounds.S, Word.Vowels.AA, Word.Group.NONE),
	Word.new("smell", Word.Type.NONE, 1, Word.Rhyme.EH1_L, Word.Sounds.S, Word.Vowels.EH, Word.Group.NONE),
	Word.new("smelly", Word.Type.NONE, 2, Word.Rhyme.EH1_L_IY0, Word.Sounds.S, Word.Vowels.EH, Word.Group.NONE),
	Word.new("smoke", Word.Type.NONE, 1, Word.Rhyme.OW1_K, Word.Sounds.S, Word.Vowels.OW, Word.Group.NONE),
	Word.new("smut", Word.Type.NONE, 1, Word.Rhyme.AH1_T, Word.Sounds.S, Word.Vowels.AH, Word.Group.NONE),
	Word.new("snap", Word.Type.NONE, 1, Word.Rhyme.AE1_P, Word.Sounds.S, Word.Vowels.AE, Word.Group.NONE),
	Word.new("so-so", Word.Type.NONE, 2, Word.Rhyme.OW1, Word.Sounds.S, Word.Vowels.OW, Word.Group.NONE),
	Word.new("soda", Word.Type.NONE, 2, Word.Rhyme.OW1_D_AH0, Word.Sounds.S, Word.Vowels.OW, Word.Group.NONE),
	Word.new("songs", Word.Type.NONE, 1, Word.Rhyme.AO1_NG_Z, Word.Sounds.S, Word.Vowels.AO, Word.Group.NONE),
	Word.new("spews", Word.Type.NONE, 1, Word.Rhyme.UW1_Z, Word.Sounds.S, Word.Vowels.UW, Word.Group.NONE),
	Word.new("spiritual", Word.Type.NONE, 4, Word.Rhyme.IH1_R_IH0_CH_AH0_W_AH0_L, Word.Sounds.S, Word.Vowels.IH, Word.Group.NONE),
	Word.new("spooky", Word.Type.NONE, 2, Word.Rhyme.UW1_K_IY0, Word.Sounds.S, Word.Vowels.UW, Word.Group.NONE),
	Word.new("squirt", Word.Type.NONE, 1, Word.Rhyme.ER1_T, Word.Sounds.S, Word.Vowels.ER, Word.Group.NONE),
	Word.new("stinky", Word.Type.NONE, 2, Word.Rhyme.IH1_NG_K_IY0, Word.Sounds.S, Word.Vowels.IH, Word.Group.NONE),
	Word.new("strut", Word.Type.NONE, 1, Word.Rhyme.AH1_T, Word.Sounds.S, Word.Vowels.AH, Word.Group.NONE),
	Word.new("stupid", Word.Type.NONE, 2, Word.Rhyme.UW1_P_AH0_D, Word.Sounds.S, Word.Vowels.UW, Word.Group.NONE),
	Word.new("sublime", Word.Type.NONE, 2, Word.Rhyme.AY1_M, Word.Sounds.S, Word.Vowels.AY, Word.Group.NONE),
	Word.new("terrible", Word.Type.NONE, 3, Word.Rhyme.EH1_R_AH0_B_AH0_L, Word.Sounds.T, Word.Vowels.EH, Word.Group.NONE),
	Word.new("thereof", Word.Type.NONE, 2, Word.Rhyme.AH1_V, Word.Sounds.DH, Word.Vowels.AH, Word.Group.NONE),
	Word.new("think", Word.Type.NONE, 1, Word.Rhyme.IH1_NG_K, Word.Sounds.TH, Word.Vowels.IH, Word.Group.NONE),
	Word.new("time", Word.Type.NONE, 1, Word.Rhyme.AY1_M, Word.Sounds.T, Word.Vowels.AY, Word.Group.NONE),
	Word.new("toaster", Word.Type.NONE, 2, Word.Rhyme.OW1_S_T_ER0, Word.Sounds.T, Word.Vowels.OW, Word.Group.NONE),
	Word.new("tomato", Word.Type.NONE, 3, Word.Rhyme.EY1_T_OW2, Word.Sounds.T, Word.Vowels.EY, Word.Group.NONE),
	Word.new("tool", Word.Type.NONE, 1, Word.Rhyme.UW1_L, Word.Sounds.T, Word.Vowels.UW, Word.Group.NONE),
	Word.new("trash", Word.Type.NONE, 1, Word.Rhyme.AE1_SH, Word.Sounds.T, Word.Vowels.AE, Word.Group.NONE),
	Word.new("truck", Word.Type.NONE, 1, Word.Rhyme.AH1_K, Word.Sounds.T, Word.Vowels.AH, Word.Group.NONE),
	Word.new("tweet", Word.Type.NONE, 1, Word.Rhyme.IY1_T, Word.Sounds.T, Word.Vowels.IY, Word.Group.NONE),
	Word.new("verses", Word.Type.NONE, 2, Word.Rhyme.ER1_S_AH0_Z, Word.Sounds.V, Word.Vowels.ER, Word.Group.NONE),
	Word.new("walk", Word.Type.NONE, 1, Word.Rhyme.AO1_K, Word.Sounds.W, Word.Vowels.AO, Word.Group.NONE),
	Word.new("wallstreet", Word.Type.NONE, 2, Word.Rhyme.AO1_L_S_T_R_IY2_T, Word.Sounds.W, Word.Vowels.AO, Word.Group.NONE),
	Word.new("water", Word.Type.NONE, 2, Word.Rhyme.AO1_T_ER0, Word.Sounds.W, Word.Vowels.AO, Word.Group.NONE),
	Word.new("winner", Word.Type.NONE, 2, Word.Rhyme.IH1_N_ER0, Word.Sounds.W, Word.Vowels.IH, Word.Group.NONE),
	Word.new("winning", Word.Type.NONE, 2, Word.Rhyme.IH1_N_IH0_NG, Word.Sounds.W, Word.Vowels.IH, Word.Group.NONE),
	Word.new("write", Word.Type.NONE, 1, Word.Rhyme.AY1_T, Word.Sounds.R, Word.Vowels.AY, Word.Group.NONE),
	Word.new("writing", Word.Type.NONE, 2, Word.Rhyme.AY1_T_IH0_NG, Word.Sounds.R, Word.Vowels.AY, Word.Group.NONE),
	Word.new("wrongs", Word.Type.NONE, 1, Word.Rhyme.AO1_NG_Z, Word.Sounds.R, Word.Vowels.AO, Word.Group.NONE),
	Word.new("yap", Word.Type.NONE, 1, Word.Rhyme.AE1_P, Word.Sounds.Y, Word.Vowels.AE, Word.Group.NONE),
	Word.new("you", Word.Type.NONE, 1, Word.Rhyme.UW1, Word.Sounds.Y, Word.Vowels.UW, Word.Group.NONE),
	Word.new("zeal", Word.Type.NONE, 1, Word.Rhyme.IY1_L, Word.Sounds.Z, Word.Vowels.IY, Word.Group.NONE),
	Word.new("affair", Word.Type.NONE, 2, Word.Rhyme.EH1_R, Word.Sounds.AH, Word.Vowels.EH, Word.Group.NONE),
	Word.new("awake", Word.Type.NONE, 2, Word.Rhyme.EY1_K, Word.Sounds.AH, Word.Vowels.EY, Word.Group.NONE),
	Word.new("bake", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.B, Word.Vowels.EY, Word.Group.NONE),
	Word.new("baloney", Word.Type.NONE, 3, Word.Rhyme.OW1_N_IY0, Word.Sounds.B, Word.Vowels.OW, Word.Group.NONE),
	Word.new("band", Word.Type.NONE, 1, Word.Rhyme.AE1_N_D, Word.Sounds.B, Word.Vowels.AE, Word.Group.NONE),
	Word.new("bloke", Word.Type.NONE, 1, Word.Rhyme.OW1_K, Word.Sounds.B, Word.Vowels.OW, Word.Group.NONE),
	Word.new("boor", Word.Type.NONE, 1, Word.Rhyme.UH1_R, Word.Sounds.B, Word.Vowels.UH, Word.Group.NONE),
	Word.new("bop", Word.Type.NONE, 1, Word.Rhyme.AA1_P, Word.Sounds.B, Word.Vowels.AA, Word.Group.NONE),
	Word.new("bored", Word.Type.NONE, 1, Word.Rhyme.AO1_R_D, Word.Sounds.B, Word.Vowels.AO, Word.Group.NONE),
	Word.new("break", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.B, Word.Vowels.EY, Word.Group.NONE),
	Word.new("bunch", Word.Type.NONE, 1, Word.Rhyme.AH1_N_CH, Word.Sounds.B, Word.Vowels.AH, Word.Group.NONE),
	Word.new("buy", Word.Type.NONE, 1, Word.Rhyme.AY1, Word.Sounds.B, Word.Vowels.AY, Word.Group.NONE),
	Word.new("bye", Word.Type.NONE, 1, Word.Rhyme.AY1, Word.Sounds.B, Word.Vowels.AY, Word.Group.NONE),
	Word.new("cake", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.K, Word.Vowels.EY, Word.Group.NONE),
	Word.new("canned", Word.Type.NONE, 1, Word.Rhyme.AE1_N_D, Word.Sounds.K, Word.Vowels.AE, Word.Group.NONE),
	Word.new("care", Word.Type.NONE, 1, Word.Rhyme.EH1_R, Word.Sounds.K, Word.Vowels.EH, Word.Group.NONE),
	Word.new("cash", Word.Type.NONE, 1, Word.Rhyme.AE1_SH, Word.Sounds.K, Word.Vowels.AE, Word.Group.NONE),
	Word.new("chair", Word.Type.NONE, 1, Word.Rhyme.EH1_R, Word.Sounds.CH, Word.Vowels.EH, Word.Group.NONE),
	Word.new("choke", Word.Type.NONE, 1, Word.Rhyme.OW1_K, Word.Sounds.CH, Word.Vowels.OW, Word.Group.NONE),
	Word.new("choked", Word.Type.NONE, 1, Word.Rhyme.OW1_K_T, Word.Sounds.CH, Word.Vowels.OW, Word.Group.NONE),
	Word.new("chop", Word.Type.NONE, 1, Word.Rhyme.AA1_P, Word.Sounds.CH, Word.Vowels.AA, Word.Group.NONE),
	Word.new("cigarette", Word.Type.NONE, 3, Word.Rhyme.EH1_T, Word.Sounds.S, Word.Vowels.EH, Word.Group.NONE),
	Word.new("corn", Word.Type.NONE, 1, Word.Rhyme.AO1_R_N, Word.Sounds.K, Word.Vowels.AO, Word.Group.NONE),
	Word.new("croak", Word.Type.NONE, 1, Word.Rhyme.OW1_K, Word.Sounds.K, Word.Vowels.OW, Word.Group.NONE),
	Word.new("crunch", Word.Type.NONE, 1, Word.Rhyme.AH1_N_CH, Word.Sounds.K, Word.Vowels.AH, Word.Group.NONE),
	Word.new("debt", Word.Type.NONE, 1, Word.Rhyme.EH1_T, Word.Sounds.D, Word.Vowels.EH, Word.Group.NONE),
	Word.new("debtor", Word.Type.NONE, 2, Word.Rhyme.EH1_T_ER0, Word.Sounds.D, Word.Vowels.EH, Word.Group.NONE),
	Word.new("die", Word.Type.NONE, 1, Word.Rhyme.AY1, Word.Sounds.D, Word.Vowels.AY, Word.Group.NONE),
	Word.new("discord", Word.Type.NONE, 2, Word.Rhyme.IH1_S_K_AO0_R_D, Word.Sounds.D, Word.Vowels.IH, Word.Group.NONE),
	Word.new("drake", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.D, Word.Vowels.EY, Word.Group.NONE),
	Word.new("flake", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.F, Word.Vowels.EY, Word.Group.NONE),
	Word.new("flop", Word.Type.NONE, 1, Word.Rhyme.AA1_P, Word.Sounds.F, Word.Vowels.AA, Word.Group.NONE),
	Word.new("fly", Word.Type.NONE, 1, Word.Rhyme.AY1, Word.Sounds.F, Word.Vowels.AY, Word.Group.NONE),
	Word.new("forbid", Word.Type.NONE, 2, Word.Rhyme.IH1_D, Word.Sounds.F, Word.Vowels.IH, Word.Group.NONE),
	Word.new("glare", Word.Type.NONE, 1, Word.Rhyme.EH1_R, Word.Sounds.G, Word.Vowels.EH, Word.Group.NONE),
	Word.new("glop", Word.Type.NONE, 1, Word.Rhyme.AA1_P, Word.Sounds.G, Word.Vowels.AA, Word.Group.NONE),
	Word.new("gore", Word.Type.NONE, 1, Word.Rhyme.AO1_R, Word.Sounds.G, Word.Vowels.AO, Word.Group.NONE),
	Word.new("gourd", Word.Type.NONE, 1, Word.Rhyme.AO1_R_D, Word.Sounds.G, Word.Vowels.AO, Word.Group.NONE),
	Word.new("government", Word.Type.NONE, 3, Word.Rhyme.AH1_V_ER0_M_AH0_N_T, Word.Sounds.G, Word.Vowels.AH, Word.Group.NONE),
	Word.new("hair", Word.Type.NONE, 1, Word.Rhyme.EH1_R, Word.Sounds.HH, Word.Vowels.EH, Word.Group.NONE),
	Word.new("honey", Word.Type.NONE, 2, Word.Rhyme.AH1_N_IY0, Word.Sounds.HH, Word.Vowels.AH, Word.Group.NONE),
	Word.new("ignored", Word.Type.NONE, 2, Word.Rhyme.AO1_R_D, Word.Sounds.IH, Word.Vowels.AO, Word.Group.NONE),
	Word.new("lair", Word.Type.NONE, 1, Word.Rhyme.EH1_R, Word.Sounds.L, Word.Vowels.EH, Word.Group.NONE),
	Word.new("lonely", Word.Type.NONE, 2, Word.Rhyme.OW1_N_L_IY0, Word.Sounds.L, Word.Vowels.OW, Word.Group.NONE),
	Word.new("lunch", Word.Type.NONE, 1, Word.Rhyme.AH1_N_CH, Word.Sounds.L, Word.Vowels.AH, Word.Group.NONE),
	Word.new("lure", Word.Type.NONE, 1, Word.Rhyme.UH1_R, Word.Sounds.L, Word.Vowels.UH, Word.Group.NONE),
	Word.new("mild", Word.Type.NONE, 1, Word.Rhyme.AY1_L_D, Word.Sounds.M, Word.Vowels.AY, Word.Group.NONE),
	Word.new("mistake", Word.Type.NONE, 2, Word.Rhyme.EY1_K, Word.Sounds.M, Word.Vowels.EY, Word.Group.NONE),
	Word.new("money", Word.Type.NONE, 2, Word.Rhyme.AH1_N_IY0, Word.Sounds.M, Word.Vowels.AH, Word.Group.NONE),
	Word.new("mop", Word.Type.NONE, 1, Word.Rhyme.AA1_P, Word.Sounds.M, Word.Vowels.AA, Word.Group.NONE),
	Word.new("mourn", Word.Type.NONE, 1, Word.Rhyme.AO1_R_N, Word.Sounds.M, Word.Vowels.AO, Word.Group.NONE),
	Word.new("munch", Word.Type.NONE, 1, Word.Rhyme.AH1_N_CH, Word.Sounds.M, Word.Vowels.AH, Word.Group.NONE),
	Word.new("pet", Word.Type.NONE, 1, Word.Rhyme.EH1_T, Word.Sounds.P, Word.Vowels.EH, Word.Group.NONE),
	Word.new("phoney", Word.Type.NONE, 2, Word.Rhyme.OW1_N_IY0, Word.Sounds.F, Word.Vowels.OW, Word.Group.NONE),
	Word.new("pore", Word.Type.NONE, 1, Word.Rhyme.AO1_R, Word.Sounds.P, Word.Vowels.AO, Word.Group.NONE),
	Word.new("quake", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.K, Word.Vowels.EY, Word.Group.NONE),
	Word.new("record", Word.Type.NONE, 2, Word.Rhyme.AO1_R_D, Word.Sounds.R, Word.Vowels.AO, Word.Group.NONE),
	Word.new("ruler", Word.Type.NONE, 2, Word.Rhyme.UW1_L_ER0, Word.Sounds.R, Word.Vowels.UW, Word.Group.NONE),
	Word.new("sand", Word.Type.NONE, 1, Word.Rhyme.AE1_N_D, Word.Sounds.S, Word.Vowels.AE, Word.Group.NONE),
	Word.new("scrunch", Word.Type.NONE, 1, Word.Rhyme.AH1_N_CH, Word.Sounds.S, Word.Vowels.AH, Word.Group.NONE),
	Word.new("shake", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.SH, Word.Vowels.EY, Word.Group.NONE),
	Word.new("skid", Word.Type.NONE, 1, Word.Rhyme.IH1_D, Word.Sounds.S, Word.Vowels.IH, Word.Group.NONE),
	Word.new("slop", Word.Type.NONE, 1, Word.Rhyme.AA1_P, Word.Sounds.S, Word.Vowels.AA, Word.Group.NONE),
	Word.new("smell", Word.Type.NONE, 1, Word.Rhyme.EH1_L, Word.Sounds.S, Word.Vowels.EH, Word.Group.NONE),
	Word.new("snake", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.S, Word.Vowels.EY, Word.Group.NONE),
	Word.new("square", Word.Type.NONE, 1, Word.Rhyme.EH1_R, Word.Sounds.S, Word.Vowels.EH, Word.Group.NONE),
	Word.new("stand", Word.Type.NONE, 1, Word.Rhyme.AE1_N_D, Word.Sounds.S, Word.Vowels.AE, Word.Group.NONE),
	Word.new("stepchild", Word.Type.NONE, 2, Word.Rhyme.EH1_P_CH_AY2_L_D, Word.Sounds.S, Word.Vowels.EH, Word.Group.NONE),
	Word.new("stillborn", Word.Type.NONE, 2, Word.Rhyme.AO1_R_N, Word.Sounds.S, Word.Vowels.IH, Word.Group.NONE),
	Word.new("sword", Word.Type.NONE, 1, Word.Rhyme.AO1_R_D, Word.Sounds.S, Word.Vowels.AO, Word.Group.NONE),
	Word.new("taste", Word.Type.NONE, 1, Word.Rhyme.EY1_S_T, Word.Sounds.T, Word.Vowels.EY, Word.Group.NONE),
	Word.new("tear", Word.Type.NONE, 1, Word.Rhyme.EH1_R, Word.Sounds.T, Word.Vowels.EH, Word.Group.NONE),
	Word.new("the", Word.Type.NONE, 1, Word.Rhyme.DH_AH0, Word.Sounds.DH, Word.Vowels.AH, Word.Group.NONE),
	Word.new("try", Word.Type.NONE, 1, Word.Rhyme.AY1, Word.Sounds.T, Word.Vowels.AY, Word.Group.NONE),
	Word.new("wake", Word.Type.NONE, 1, Word.Rhyme.EY1_K, Word.Sounds.W, Word.Vowels.EY, Word.Group.NONE),
	Word.new("wet", Word.Type.NONE, 1, Word.Rhyme.EH1_T, Word.Sounds.W, Word.Vowels.EH, Word.Group.NONE),
	Word.new("wetter", Word.Type.NONE, 2, Word.Rhyme.EH1_T_ER0, Word.Sounds.W, Word.Vowels.EH, Word.Group.NONE),
	Word.new("woke", Word.Type.NONE, 1, Word.Rhyme.OW1_K, Word.Sounds.W, Word.Vowels.OW, Word.Group.NONE),
	Word.new("yarn", Word.Type.NONE, 1, Word.Rhyme.AA1_R_N, Word.Sounds.Y, Word.Vowels.AA, Word.Group.NONE),
]

static var player_words_manual : Array[Word] = [
	Word.new("back seat", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("bereft of", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("bleat", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("blowhead", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("booby trap", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("cant compete", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("cash flow", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("dead meat", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("dirt hog", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("doh!", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("dongs", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("foot clog", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("jo-schmo", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("lamest", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("lymph cell", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("meat hooks", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("no cap", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("peeing", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("pooping", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("psychodrama", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("rap sheet", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("self-love", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("shmooze", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("silly-billy", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("squee", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("stepfather ", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("sugar mama", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("take a seat", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("toilet seat", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("weeeee!", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("wet feet", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("willy-nilly", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("baguette", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("c.i.a", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("cooky", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("crueller", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("f.b.i", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("ferrofluid", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("foreswear", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("hog wild", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("mewler", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("onely", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("pigsty", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("the man", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
	Word.new("white collar criminal", Word.Type.NONE, 0, Word.Rhyme.NONE, Word.Sounds.NONE, Word.Vowels.NONE, Word.Group.NONE),
]

# TODO:
"""
back seat
bereft of
bleat
blowhead
booby trap
cant compete
cash flow
dead meat
dirt hog
doh!
dongs
foot clog
jo-schmo
lamest
lymph cell
meat hooks
no cap
peeing
pooping
psychodrama
rap sheet
self-love
shmooze
silly-billy
squee
stepfather 
sugar mama
take a seat
toilet seat
weeeee!
wet feet
willy-nilly
baguette
c.i.a
cooky
crueller
f.b.i
ferrofluid
foreswear
hog wild
mewler
onely
pigsty
the man
white collar criminal
"""
