words = set(" ".join([
"You look like a ____",
"You smell like a ____",
"I’d rather be ____",
"You’re taking the ____",
"I’m better than ____",
"I’m cooler than ____",
"You're lamer than ____",
"I’m smarter than ____",
"You're stupider than ____",
"Where did you ____?",
"Why are you ____?",
"Stop being ____",
"I’ll ____ you for real",
"You cannot ____ me",
"Take a ____ ____",
"You are ____ ____",
"You look like my ____",
"Your momma so ____",
"____",
"And those shoes? ____",
"So broke, so ____",
"Your haircut look ____",
"Only ____ could be your fan",
"You can’t even ____",
"You couldn't even afford ____",
"Your head looks like a ____",
"Bet you couldn’t even take a ____",
"You seem a love child born of ____",
"I see you drove here in a ____",
"You're fake as hell, you'll only ever be a ____",
"You ____ like a ____",
# "brain",
# "simple",
# "smoked",
# "truck",
# "duck",
# "brick",
# "Fish",
# "Garbage",
# "Dumpster",
# "Cheese",
# "L",
# "You",
# "Me",
# "Anyone",
# "Loser",
# "Winner",
# "Dinner",
# "Chicken",
# "Potato",
# "Tomato",
# "Water",
# "Father",
# "Mother",
# "Sister",
# "Brother",
# "Fool",
# "School",
# "Tool",
# "Bars",
# "Cars",
# "Flows",
# "Rhymes",
# "Lyrics",
# "Songs",
# "Verses",
# "Dog",
# "Cat",
# "Rat",
# "Gun",
# "Bat",
# "Knife",
# "Ball",
# "Pizza",
# "Soda",
# "Burger",
# "Toaster",
# "Blender",
# "Microwave",
# "Fridge",
# "Keyboard",
# "Pen",
# "Pencil",
# "Run",
# "Walk",
# "Rap",
# "Bounce",
# "Play",
# "Eat",
# "Drink",
# "Poop",
# "Pee",
# "Learn",
# "Sing",
# "Write",
# "Love",
# "Hate",
# "Trash",
# "Plane",
# "Jet",
# "Rapping",
# "Writing",
# "Winning",
# "Losing",
# "Balling",
# "Pooping",
# "Peeing",
# "Singing",
# "Eating",
# "Drinking",
# "Loving",
# "Hating",
# "Stinky",
# "Smelly",
# "Awesome",
# "Greatest",
# "Lamest",
# "Great",
# "Lame",
# "Stupid",
# "Silly",
# "Crazy",
# "Amazing",
# "Spooky",
# "Funny",
# "Awful",
# "Terrible",
# "Bad",
# "Good",
# "Shocking",
# "Confusing",
# "Mediocre",
# "So-so",
# "Mid",
]).split(" "))
print("\n".join(sorted(words)))